version: '3.8'

services:
    db:
        image: mysql:8
        container_name: starterkit-db
        restart: always
        environment:
            MYSQL_DATABASE: starterkit
            MYSQL_USER: starterkit_user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./volumes/starterkit-db:/var/lib/mysql
        healthcheck:
            test: mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
            interval: 5s
            timeout: 20s
            retries: 10
        ports: [ '3307:3306' ]
        command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"
    minio:
        image: minio/minio
        container_name: starterkit-minio
        environment:
            MINIO_ROOT_USER: user
            MINIO_ROOT_PASSWORD: password
            MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
            MINIO_SERVER_URL: http://localhost:9000
        volumes:
            - ./volumes/starterkit-minio:/minio
        healthcheck:
            test: ["CMD", "mc", "ready", "local"]
            interval: 5s
            timeout: 5s
            retries: 5
        ports: [ '9000:9000', '9001:9001' ]
        command:  server /minio --console-address ":9001"